In [3]:
import pandas
import pandas as pd
import numpy as np
import os

In [10]:
#read csv file
datasets = pd.read_csv('./Desktop/pythonProject/data.csv')
datasets = datasets.iloc[:,1:6]
print(datasets)

        Age Work Own_Apartment Credit_History response
0       Old  Yes            No       Moderate      Yes
1     Young  Yes            No           Good      Yes
2       Old  Yes            No       Moderate      Yes
3    Middle  Yes           Yes       Moderate      Yes
4     Young  Yes            No       Moderate      Yes
..      ...  ...           ...            ...      ...
495     Old   No           Yes           Good      Yes
496   Young   No            No           Good       No
497     Old  Yes            No           Good       No
498  Middle   No           Yes           Good      Yes
499     Old   No           Yes      Excellent      Yes

[500 rows x 5 columns]


In [12]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

In [13]:
# label encoder
label_encoder = LabelEncoder()
Y = label_encoder.fit_transform(datasets['response'])
print(Y)

[1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 0 0 1 1 0 1 0 1 1 1 0 1 1 1 1 1 0
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 1 1 1 0 0 0 0 1 1 1 0 1 1 1 0
 0 1 0 0 0 1 0 0 1 0 0 1 1 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 1 0 1 1 0 0 1 1 0
 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 0 0 1 1 0 1 0 1 1 1 0 0 0 1 0 0 1 0
 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 0 1 0 1 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 1 0 1
 1 1 1 0 0 0 1 1 0 0 0 1 0 1 1 1 1 0 1 1 1 0 0 0 1 0 1 1 1 1 1 0 0 1 0 1 1
 0 0 1 1 1 1 0 1 1 0 1 1 1 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 1 0 1
 0 0 1 0 1 1 1 1 0 1 1 0 0 0 0 1 1 0 1 0 0 1 1 0 1 0 1 1 1 1 0 1 1 0 1 0 1
 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 1 0 1 0 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0
 1 1 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 1 1 1 0 1 0
 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 0 1 0 0 1 1 0 1 0 1 1
 1 1 0 1 0 1 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 1 0 1 0 1 1 1 1 1 1 0 0 0 1 0
 0 1 1 1 1 1 1 0 1 0 1 1 0 0 1 1 1 0 0 1 1 0 0 0 1 1 1 1 0 1 1 0 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 0 0 1 

In [14]:
# ordinal encoder
ord_enc = OrdinalEncoder()
datasets = ord_enc.fit_transform(datasets)
datasets = pd.DataFrame(datasets,columns=['Age','Work','Own_Apartment','Credit_History','response'])

print(datasets)

     Age  Work  Own_Apartment  Credit_History  response
0    1.0   1.0            0.0             2.0       1.0
1    2.0   1.0            0.0             1.0       1.0
2    1.0   1.0            0.0             2.0       1.0
3    0.0   1.0            1.0             2.0       1.0
4    2.0   1.0            0.0             2.0       1.0
..   ...   ...            ...             ...       ...
495  1.0   0.0            1.0             1.0       1.0
496  2.0   0.0            0.0             1.0       0.0
497  1.0   1.0            0.0             1.0       0.0
498  0.0   0.0            1.0             1.0       1.0
499  1.0   0.0            1.0             0.0       1.0

[500 rows x 5 columns]


In [24]:
# define function to calculate entopy
def entropy(datasets, Y):

    y_unique = list(set(Y))
    # Calculate Prior Probability
    prior = np.zeros(len(y_unique))
    
    prior =[]

    for i in range(0, len(y_unique)):
        prior_sum= sum(Y == y_unique[i]) / len(Y)
        prior.append(prior_sum)

    entropy = 0

    for i in range(0, len(y_unique)):
        entropy_sum = -1 * prior[i] * np.log2(prior[i])
        entropy += entropy_sum


    return entropy

In [25]:
# calculate entropy
entropy_test = entropy(datasets, Y)
print('entropy test:',entropy_test)

entropy test: 0.9754383526853787


In [26]:
# define function to calculate conditional entropy

def conditional_entropy(datasets, col, Y):
    
    var = list(datasets.columns)[col]
    var_unique = list(set(datasets[var]))
    
    y_unique = list(set(Y))
    y_len = len(y_unique)
    
    # calculate conditional probability
    prob = np.zeros([len(var_unique), y_len + 1])

    for i in range(0, len(var_unique)):
        prob[i, 0] = sum(datasets[var] == var_unique[i]) / len(datasets[var])
        
    #print(conditional_prob)
    for i in range(0, len(var_unique)):
        for j in range(0, len(y_unique)):
            prob[i, j + 1] = \
            datasets.loc[(datasets[var] == var_unique[i]) & (Y == y_unique[j]),].shape[0] / sum(
                datasets[var] == var_unique[i])

    # calculate conditional entropy
    cond_entropy = 0
    for i in range(0, len(var_unique)):
        if (prob[i, 1] != 0) & (prob[i, 2] != 0):
            enp = -1 * prob[i, 0] * (prob[i, 1] * np.log2(prob[i, 1]) + prob[i, 2] * np.log2(prob[i, 2]))
            
        elif (prob[i, 1] == 0) & (prob[i, 2] != 0):
            enp = -1 * prob[i, 0] * (prob[i, 2] * np.log2(prob[i, 2], len(y_unique)))
            
        elif (prob[i, 1] != 0) & (prob[i, 2] == 0):
            enp = -1 * prob[i, 0] * (prob[i, 1] * np.log2(prob[i, 1], len(y_unique)))

        cond_entropy += enp

    return cond_entropy

In [27]:
cond_entropy = conditional_entropy(datasets=datasets, col=0, Y=Y)
print('cond_entropy:',cond_entropy)

cond_entropy: 0.934122296766307


In [34]:
from  sklearn.metrics import confusion_matrix


X = datasets.iloc[:,:4]
X = np.array(X)

Y=Y

#read test data csv file
test_data = pandas.read_csv('./Desktop/pythonProject/test1.csv')
test_data = test_data.iloc[:,1:6]

ord_enc = OrdinalEncoder()
X_test = ord_enc.fit_transform(test_data)
X_test = pd.DataFrame(X_test,columns=['Age','Work','Own_Apartment','Credit_History','response'])
X_test = X_test.iloc[:,:4]

label_encoder = LabelEncoder()
Y_test = label_encoder.fit_transform(test_data['response'])

In [36]:
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings("ignore")

model1 = LogisticRegression()
model1.fit(X,Y)

y_pred1 = model1.predict(X_test)

w1_cm = confusion_matrix(Y_test, y_pred1)

print('w1_cm:',w1_cm)

w1_cm: [[3 2]
 [3 7]]


In [37]:
from sklearn.naive_bayes import GaussianNB

model2 = GaussianNB()
model2.fit(X,Y)

y_pred2 = model2.predict(X_test)

w2_cm = confusion_matrix(Y_test, y_pred2)

print('w2_cm:',w2_cm)

w2_cm: [[3 2]
 [3 7]]


In [38]:
from sklearn import svm

model3 = svm.SVC()
model3.fit(X,Y)

y_pred3 = model3.predict(X_test)

w3_cm = confusion_matrix(Y_test, y_pred3)

print('w3_cm:',w3_cm)

w3_cm: [[3 2]
 [1 9]]


In [39]:
from sklearn.neighbors import  KNeighborsClassifier

model4 = KNeighborsClassifier()
model4.fit(X,Y)

y_pred4 = model4.predict(X_test)

w4_cm = confusion_matrix(Y_test, y_pred4)

print('w4_cm:',w4_cm)

w4_cm: [[4 1]
 [1 9]]


In [40]:
# create worker predicted matrix
worker  = (y_pred1,y_pred2,y_pred3,y_pred4)

worker = np.vstack(worker)

print(worker)

[[1 1 1 1 0 0 1 1 1 1 0 1 0 0 0]
 [1 1 1 1 0 0 1 1 1 1 0 1 0 0 0]
 [1 1 0 1 1 1 1 1 1 1 0 1 0 0 1]
 [1 1 0 1 1 0 1 1 1 1 1 1 0 0 0]]


In [41]:
def get_prob(Y_test):

    y_unique = list(set(Y_test))
    
    # Calculate probability
    prior_prob = np.zeros(len(y_unique))
    
    prior_d = {}
    for i in range(0, len(y_unique)):
        prior= sum(Y_test == y_unique[i]) / len(Y_test)
        prior_d[y_unique[i]] = prior

    return prior_d

In [42]:
#get probability of actual Y_test data set

prob_y  = get_prob(Y_test)
print(prob_y)

{0: 0.3333333333333333, 1: 0.6666666666666666}


In [ ]:
# calculate probability of sum(log(p(P(Xij = xij|Yj = c))) 